# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import revista.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=revista.utils.get_file_path)),
                ('frase', models.TextField()),
                ('autor', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='FotosPortada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Fotos portada',
                'verbose_name_plural': 'Fotos de las Portadas',
            },
        ),
        migrations.AddField(
            model_name='fotos',
            name='portada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotosportada.FotosPortada'),
        ),
    ]
