# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotosportada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotos',
            options={'ordering': ('id',), 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AddField(
            model_name='fotos',
            name='autor_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fotos',
            name='frase_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
