# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-17 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='idarticulo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='autores',
            old_name='idautor',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='enlaces',
            old_name='idenlace',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='idenvio',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='idiomas',
            old_name='ididioma',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='idpais',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='temas',
            old_name='idtema',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='idtipo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='zonas',
            old_name='idzona',
            new_name='id',
        ),
    ]
