# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-20 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revista.Autores', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='idzona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revista.Zonas', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='opinion',
            field=models.IntegerField(blank=True, choices=[(1, 'Opinion'), (2, 'Speaking-Out'), (3, 'Analisis'), (4, 'The Month'), (5, 'Close-Up')], null=True, verbose_name='Categor\xedas en ingl\xe9s'),
        ),
    ]
