# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-17 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_auto_20171117_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportArticle',
        ),
        migrations.DeleteModel(
            name='ExportRevistas',
        ),
        migrations.DeleteModel(
            name='ExportRevistasDetalle',
        ),
        migrations.DeleteModel(
            name='PgTsCfg',
        ),
        migrations.DeleteModel(
            name='PgTsCfgmap',
        ),
        migrations.RemoveField(
            model_name='autores',
            name='nombre_it',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='tema_it',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='tipo_it',
        ),
        migrations.RemoveField(
            model_name='zonas',
            name='zona_it',
        ),
    ]
