# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_auto_20160913_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revistas',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revista.ColoresRevista'),
        ),
    ]
