# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-17 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_auto_20171117_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='idautor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='ididioma',
            new_name='idioma',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='idxtexto',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='textoidx',
        ),
        migrations.AddField(
            model_name='articulos',
            name='temas',
            field=models.ManyToManyField(blank=True, to='revista.Temas'),
        ),
    ]
