# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 06:44
from __future__ import unicode_literals

from django.db import migrations
import revista.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_auto_20160913_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ['id'], 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AddField(
            model_name='revistas',
            name='portada',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=revista.utils.get_file_path),
        ),
    ]
