# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-17 21:30
from __future__ import unicode_literals

from django.db import migrations
import revista.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0005_articulos_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='revistas',
            name='portada',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=revista.utils.get_file_path),
        ),
    ]
