# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0006_revistas_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoresRevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(blank=True, max_length=50, null=True)),
                ('color2', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='ididioma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revista.Idiomas'),
        ),
        migrations.AddField(
            model_name='revistas',
            name='colores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revista.ColoresRevista'),
        ),
    ]
