# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-22 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0009_transfer_idiomas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='idarticulo',
        ),
        migrations.AlterModelOptions(
            name='idiomas',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='revistas',
            name='color',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
