# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-22 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0010_auto_20171122_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='ididioma',
            new_name='idioma',
        ),
        migrations.RenameField(
            model_name='revistas',
            old_name='colores',
            new_name='color',
        ),
    ]
